/**
 * 
 */
package com.aric.esb.ws;

import javax.xml.namespace.QName;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import com.aric.esb.ArgumentBundle;
import com.aric.esb.arguments.Argument;
import com.aric.esb.arguments.SimpleArgument;
import com.aric.esb.resourcefactory.WsResourceFactory;

/**
 * @author Dursun KOC
 * 
 */
public class WSCallerTest {

	/**
	 * @throws java.lang.Exception
	 */
	@Before
	public void setUp() throws Exception {
	}

	/**
	 * @throws java.lang.Exception
	 */
	@After
	public void tearDown() throws Exception {
	}

	/**
	 * Test method for
	 * {@link com.aric.esb.ws.WsCaller#call(com.aric.esb.ArgumentBundle)}.
	 */
	@Test
	public void testCallWithJAX_WS() throws Exception {
		/*
		 * <?xml version='1.0' encoding='UTF-8'?><!-- Published by JAX-WS RI at http://jax-ws.dev.java.net. RI's version is Oracle JAX-WS 2.1.5. --><!-- Generated by JAX-WS RI at http://jax-ws.dev.java.net. RI's version is Oracle JAX-WS 2.1.5. --><definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://jax_ws.samples.aric.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://jax_ws.samples.aric.com/" name="JAXWSSampleService">
<types> <xsd:schema> <xsd:import namespace="http://jax_ws.samples.aric.com/" schemaLocation="http://localhost:7001/SampleWS-JAX_WS/JAXWSSampleService?xsd=1"/>
</xsd:schema> </types> <message name="hello"> <part name="parameters" element="tns:hello"/>
</message> <message name="helloResponse"> <part name="parameters" element="tns:helloResponse"/>
</message> <portType name="JAXWSSample">
<operation name="hello">
<input message="tns:hello"/>
<output message="tns:helloResponse"/>
</operation>
</portType>
<binding name="JAXWSSamplePortBinding" type="tns:JAXWSSample">
<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
<operation name="hello">
<soap:operation soapAction=""/>
<input>
<soap:body use="literal"/>
</input>
<output>
<soap:body use="literal"/>
</output>
</operation>
</binding>
<service name="JAXWSSampleService">
<port name="JAXWSSamplePort" binding="tns:JAXWSSamplePortBinding">
<soap:address location="http://localhost:7001/SampleWS-JAX_WS/JAXWSSampleService"/>
</port>
</service>
</definitions>
		 */
		WsCaller caller = new WsCaller(
				new QName("http://jax_ws.samples.aric.com/", "hello"),
				"http://localhost:7001/SampleWS-JAX_WS/JAXWSSampleService?WSDL",
				new WsResourceFactory());
		ArgumentBundle argumentBundle = new ArgumentBundle(
				new Argument[] { new SimpleArgument("arg0", "hell o world") });
		Object[] call = caller.call(argumentBundle);
		System.out.println(call[0]);
	}

}
